config/routes.rb
Rails.application.routes.draw do
  get 'contact', to: 'contact#form', as: 'contact_form'
  post 'contact-submit', to: 'contact#submit', as: 'contact_form_submit'
  
  concern :gbl_exportable, Geoblacklight::Routes::Exportable.new
  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :gbl_exportable
  end

  concern :gbl_wms, Geoblacklight::Routes::Wms.new
  namespace :wms do
    concerns :gbl_wms
  end

  concern :gbl_downloadable, Geoblacklight::Routes::Downloadable.new
  namespace :download do
    concerns :gbl_downloadable
  end

  resources :download, only: [:show]

  mount Geoblacklight::Engine => 'geoblacklight'
  mount Blacklight::Engine => '/'
  root to: "catalog#index"
    concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
  end

  devise_for :users
  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  
  def form
    @issue_types = Rails.application.config.issue_types
  end

  def submit
    ContactMailer.new_contact(params['name'], params['email'], params['subject'], params['category'], params['message']).deliver_later
    flash[:success] = "Your message has been sent. Thank you for contacting #{t('blacklight.application_name')}."
    redirect_to contact_form_path
  end

end

app/helpers/contact_helper.rb
module ContactHelper
end

app/views/contact/_directions.html.erb
Please use the contact form to submit inquiries about <%=t('blacklight.application_name') %> in general, to report a problem you are experiencing with the system, to request assistance using <%=t('blacklight.application_name') %>; or to provide feedback.

app/views/contact/form.html.erb
<h1>Contact</h1>

<div class="panel panel-default">
  <div class="panel-body">
    <%= render 'directions' %>
  </div>
</div>

<% if user_signed_in? %>
  <% em = current_user.email %>
<% else %>
  <% em = '' %>
<% end %>

<h2>Contact Form</h2>
<%= form_tag( contact_form_submit_path, {class: 'form-horizontal well'} ) do %>
  <%= text_field_tag :contact_method, nil, class: 'hide' %>
  <div class="form-group">
    <%= label_tag :category, 'Issue Type', class: "col-sm-2 control-label" %>
    <% issue_types = @issue_types.dup %>
    <% issue_types.unshift(['Select an Issue Type', nil]) %>
    <div class="col-sm-10">
      <%= select_tag 'category', options_for_select(issue_types), {class: 'form-control', required: true } %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :name, 'Your Name', class: "col-sm-2 control-label" %>
    <div class="col-sm-10"><%= text_field_tag :name, nil, class: 'form-control', required: true %></div>
  </div>

  <div class="form-group">
    <%= label_tag :email, 'Your Email', class: "col-sm-2 control-label" %>
    <div class="col-sm-10"><%= text_field_tag :email, em, class: 'form-control', required: true %></div>
  </div>

  <div class="form-group">
    <%= label_tag :subject, 'Subject', class: "col-sm-2 control-label" %>
    <div class="col-sm-10"><%= text_field_tag :subject, nil, class: 'form-control', required: true %></div>
  </div>

  <div class="form-group">
    <%= label_tag :message, 'Message', class: "col-sm-2 control-label" %>
    <div class="col-sm-10"><%= text_area_tag :message, nil, rows: 4, class: 'form-control', required: true %></div>
  </div>

  <%= submit_tag "Send", class: "btn btn-primary" %>
<% end %>